export const PRODUCT_LINE_ITEM_ADAPTER = Symbol('PRODUCT_LINE_ITEM_ADAPTER');
export const SERVICE_LINE_ITEM_ADAPTER = Symbol('SERVICE_LINE_ITEM_ADAPTER');
export const ASSET_LINE_ITEM_ADAPTER = Symbol('ASSET_LINE_ITEM_ADAPTER');
